apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-refresh-website-deployment
  labels:
    app: {{ .Chart.Name }}-refresh-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-refresh-website
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-refresh-website
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-container-registry-secret
      containers:
        - name: {{ .Chart.Name }}-refresh-website
{{ tuple "covid-vaccine-spotter" . | werf_container_image | indent 10 }}
          args: ["bin/refresh-website"]
          env:
{{ tuple "covid-vaccine-spotter" . | werf_container_env | indent 12 }}
            - name: LOG_LEVEL
              value: notice
            - name: PUBLISH_SITE
              value: "true"
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secrets
