apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-walmart-find-stores-deployment
  labels:
    app: {{ .Chart.Name }}-walmart-find-stores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-walmart-find-stores
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-walmart-find-stores
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-container-registry-secret
      containers:
        - name: {{ .Chart.Name }}-walmart-find-stores
{{ tuple "covid-vaccine-spotter" . | werf_container_image | indent 10 }}
          args: ["bin/walmart-find-stores"]
          env:
{{ tuple "covid-vaccine-spotter" . | werf_container_env | indent 12 }}
            - name: LOG_LEVEL
              value: notice
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secrets
